name: CICD Pipeline For Development Environment

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    uses: digitalidf/digitalidf-actions/.github/workflows/build-push-deploy-to-ecr.yaml@v1.3.12
    with:
      account_name: 'dev'
      image: atuda-app-server-dev
      enable_latest_tag: false
      dockerfile: Dockerfile
      environment: dev

  update-image-tag:
    needs: build-and-push
    uses: digitalidf/digitalidf-actions/.github/workflows/update-image-tag.yaml@main
    with:
      repository: 'atuda-manifests'
      path_to_deployment: 'manifests/dev/atuda-bakashot/server-deployment.yaml'
      branch_to_merge: 'master'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build-and-push-seed-image:
    needs: update-image-tag
    uses: digitalidf/digitalidf-actions/.github/workflows/build-push-deploy-to-ecr.yaml@v1.3.12
    with:
      account_name: 'dev'
      image: atuda-app-seed-dev
      enable_latest_tag: false
      dockerfile: Dockerfile.seed
      environment: dev

  update-seed-image-tag:
    needs: build-and-push-seed-image
    uses: digitalidf/digitalidf-actions/.github/workflows/update-image-tag.yaml@main
    with:
      repository: 'atuda-manifests'
      path_to_deployment: 'manifests/jobs/dev-server-seed-job.yaml'
      branch_to_merge: 'master'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
